"""Regenerate ``link_screen_sites.py`` from the gate's own discovery.

Run from the repository root::

    python3 test/gen_link_screen_sites.py

It WRITES the file and takes no redirect. A redirect cannot work here: the shell
truncates the destination before this process starts, and importing the gate
module pulls in the baseline being written, so the import fails and the
truncated file is what survives. Writing from inside ``main`` reads the old
baseline first, and the write itself is staged under a unique temp name and
renamed over the destination, so an interruption or a full disk leaves the
previous baseline intact instead of a partial file nothing can import.

The baseline is generated rather than hand-written so it cannot drift from the
condition the gate actually evaluates: both come from ``discovered_sites``.
Adding a site by hand would let the list claim a shape the gate never checked.

The count is written to stderr as a sentinel, so a run that writes nothing is
distinguishable from a run that found nothing.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

# Anchored to the repo root, never a bare relative "src". Run from any other
# directory, a relative entry resolves to a nonexistent ./src, `kiro_crew` binds
# to whatever copy is installed, and this would then enumerate THAT tree while
# writing the baseline into this checkout -- with the sentinel reporting a count
# and no hint of which tree produced it.
sys.path[:0] = [str(Path(__file__).resolve().parent), str(_REPO_ROOT / "src")]

from test_link_screen_hold_pin import discovered_sites  # noqa: E402

from kiro_crew.atomic_write import atomic_write  # noqa: E402

#: The formatter's line length, which the emitted entries have to respect: a
#: generated file that fails the formatting gate makes "regenerate rather than
#: edit by hand" an instruction that cannot be followed.
LINE_LENGTH = 100

DEST = Path(__file__).resolve().parent / "link_screen_sites.py"

HEADER = '''"""The declared baseline of screen-then-resolve-by-name sites.

A site reaches this list one of two ways, and the distinction is the whole point.

Either it HOLDS its chain across the screen and the use, so the object the screen
inspected is the object the use reaches. Those sites are also named in
``HELD_SITES`` in the gate module, which asserts the shape structurally.

Or a hold is not the answer for it, because it refuses every link and never
traverses one. Tightening such a site further costs an ordinary layout -- a
junction or symlink on the path to a config directory, which a dotfile manager
produces on purpose -- and buys no privilege back.

The list is the baseline the condition's output is compared against. It is NEVER
the search key: the gate enumerates from source by the condition, so a new site
is found because it matches the shape, not because it resembles one of these.

Which of the two kinds a site is does not live here, because this file is
regenerated whole and a reason written into it would not survive. The held sites
are named in ``HELD_SITES``; anything else is recorded where a decision belongs,
in the commit that added the site and in the reviewed issue.

Generated by ``gen_link_screen_sites.py``; regenerate rather than edit by hand.
"""

'''


def _entry(module: str, func: str) -> str:
    """One baseline entry, wrapped exactly where the formatter would wrap it."""
    flat = f'        ("{module}", "{func}"),\n'
    if len(flat.rstrip("\n")) <= LINE_LENGTH:
        return flat
    return f'        (\n            "{module}",\n            "{func}",\n        ),\n'


def main() -> int:
    sites = sorted(discovered_sites())
    out = [HEADER, "DECLARED_SITES = frozenset(\n", "    {\n"]
    out += [_entry(module, func) for module, func in sites]
    out += ["    }\n", ")\n"]
    # Staged under a unique temp name and renamed over the destination, so an
    # interruption or a full disk leaves the previous baseline intact rather than a
    # truncated file that cannot be imported. `newline=""` keeps the emitted "\n"
    # verbatim, so regenerating on Windows produces the same bytes as anywhere else.
    atomic_write(DEST, "".join(out), newline="")
    print(f"SENTINEL count={len(sites)} wrote={DEST.name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
