"""Scenario: the host service definition renders correctly inside a pod's environment.

The flow being protected: someone runs ``kirocrew service install`` from a shell
that a pod has been driving. ``service install`` bakes an environment into a
systemd unit or a launchd plist, because a service starts with a minimal,
non-login environment. Two halves of that capture must behave differently, and
this pins both. ``KIROCREW_PORT`` is captured on purpose, since it is the only
input the dashboard port reads. The data home is not: it comes from the account
the service runs as, so a pod's throwaway home must never reach it, because
``pod down`` deletes that directory.

Print-only. ``service install`` has no ``--dry-run`` on POSIX, so this drives
its pure renderer. Windows has no host-service backend; there the fixture renders
the real pod Task Scheduler wrapper. Nothing is written and no service manager is
touched.

Backend dispatch lives in the fixture module, so this file has no platform
branching -- which is what makes Windows a matrix add rather than an edit here.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.timeout(300)


def test_host_service_render_captures_the_port_but_not_the_pod_home(
    pod, render_service_definition
) -> None:
    # Everything a pod exports about itself, in scope for the render.
    text = render_service_definition(
        {
            "KIROCREW_HOME": str(pod.home),
            "KIROCREW_PORT": str(pod.port),
            "KIROCREW_POD": "1",
            "KIROCREW_WORKSPACE": str(pod.home / "workspace"),
        }
    )
    assert text.strip(), "the service renderer printed nothing"

    windows_wrapper = "generated by kiro_crew.pod.windows" in text
    if windows_wrapper:
        # Windows has no host-service backend. The real service-managed artifact
        # for this suite is the per-pod Task Scheduler wrapper, and it must
        # re-enter the shipped pod runner with this exact name and plane.
        assert " pod _run " in text, f"wrapper names no pod _run command.\nrendered:\n{text}"
        assert f'"{pod.name}"' in text, f"wrapper names the wrong pod.\nrendered:\n{text}"
        assert (
            f"KIROCREW_POD_ROOT={pod.home.parent}" in text
        ), f"wrapper dropped the isolated pod root.\nrendered:\n{text}"
        # The wrapper reads the deterministic port from the pod env file at
        # _run time; it must not capture the installer's unrelated host-service
        # KIROCREW_PORT override.
        assert f"KIROCREW_PORT={pod.port}" not in text
    else:
        # The definition still describes a HOST service.
        assert "KIROCREW_SERVICE_MANAGED" in text, (
            f"the render carries no managed marker, so it lost its baked "
            f"environment.\nrendered:\n{text}"
        )
        assert "gateway" in text, f"the render names no gateway command.\nrendered:\n{text}"

        # The port IS captured from the installer's environment, by documented
        # design: KIROCREW_PORT is the only input DASHBOARD_PORT reads.
        assert f"KIROCREW_PORT={pod.port}" in text or f">{pod.port}<" in text, (
            f"the render dropped KIROCREW_PORT={pod.port} from the installer's "
            f"environment, so an installed service would fall back to the default "
            f"port.\nrendered:\n{text}"
        )

    # The HOME is the opposite case and the sharp one: it is resolved from the
    # ACCOUNT the service runs as, never from KIROCREW_HOME, so a pod's throwaway
    # home must not reach it. `pod down` deletes that directory, and a service
    # installed with it baked in would start against a path that is not there.
    assert str(pod.home) not in text, (
        f"the pod's throwaway home {pod.home} leaked into the host service "
        f"definition.\nrendered:\n{text}"
    )
    assert str(pod.home / "workspace") not in text, (
        f"the pod's throwaway workspace leaked into the host service "
        f"definition.\nrendered:\n{text}"
    )
    if windows_wrapper:
        # The wrapper MUST carry the KIROCREW_POD_* plane keys (asserted above),
        # so the pin here is narrower than the host-service one: the identity
        # marker itself, under any value, must not be baked into the task.
        assert "KIROCREW_POD=" not in text, (
            f"the pod-identity marker leaked into the Task Scheduler wrapper, which "
            f"would make the booted gateway declare itself ephemeral from the task "
            f"rather than from its own runtime.\nrendered:\n{text}"
        )
    else:
        # Broad on purpose: a host service must carry NOTHING pod-shaped -- not
        # the marker, not a plane key. Any KIROCREW_POD* in the render means the
        # installer's environment bled through.
        assert "KIROCREW_POD" not in text, (
            f"the pod-identity marker leaked into the host service definition, which "
            f"would make an installed gateway declare itself ephemeral."
            f"\nrendered:\n{text}"
        )


def test_render_names_the_home_the_service_would_run_as(pod, render_service_definition) -> None:
    """The render must name the account home the installer resolved, absolutely.

    Deliberately asserted against the renderer's OWN resolver rather than
    against ``$HOME``: the two backends resolve it differently on purpose (the
    systemd render reads the passwd entry so ``sudo -H`` cannot bake ``/root``
    in, the launchd render uses ``Path.home()``), and pinning one would make
    this scenario a platform test. What must hold on both is that the home in
    the text is the one that backend resolves, spelled absolutely.
    """
    import subprocess
    import sys

    text = render_service_definition({})
    if "generated by kiro_crew.pod.windows" in text:
        assert f'"{pod.name}"' in text, f"wrapper names the wrong pod.\nrendered:\n{text}"
        assert (
            f"KIROCREW_POD_ROOT={pod.home.parent}" in text
        ), f"wrapper does not pin the isolated plane root.\nrendered:\n{text}"
        assert str(pod.home) not in text, (
            f"wrapper captured the disposable pod HOME instead of its durable "
            f"plane.\nrendered:\n{text}"
        )
        return

    resolved = subprocess.run(
        [
            sys.executable,
            "-c",
            "from kiro_crew.service.common import Platform, current_platform\n"
            "plat = current_platform()\n"
            "if plat is Platform.SYSTEMD:\n"
            "    from kiro_crew.service import linux\n"
            "    print(linux._home_for_user(linux._current_user()))\n"
            "elif plat is Platform.LAUNCHD:\n"
            "    from pathlib import Path\n"
            "    print(Path.home())\n"
            "else:\n"
            "    from pathlib import Path\n"
            "    print(Path.home())\n",
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=120,
    )
    home = resolved.stdout.strip()
    # The systemd render resolves an absolute POSIX home from the passwd entry;
    # launchd uses Path.home(). Windows returned above after checking its real
    # Task Scheduler wrapper instead of pretending an unsupported host service
    # had a home resolver.
    import os

    assert os.path.isabs(home), f"resolver gave no absolute home: {resolved!r}"
    assert home in text, (
        f"the render does not name the home its own resolver reports "
        f"({home}).\nrendered:\n{text}"
    )
